databases:
  - name: database
    plan: free
    databaseName: portfolio_db

services:
  - type: web
    name: laravel-backend
    runtime: php
    rootDir: ./portfolio-app
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        fromService:
          type: static # Changé de 'web' à 'static'
          name: react-frontend
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password

  - type: static # Changé de 'web' à 'static'
    name: react-frontend
    rootDir: ./portfolio-app/react-app
    buildCommand: |
      npm install
      npm run build
    # Suppression de 'runtime', 'npm install -g serve' et 'startCommand'
    publicPath: ./dist # Utilisation de 'publicPath' pour les sites statiques
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: laravel-backend
          property: host
