services:
  - type: web
    name: laravel-backend
    env: php
    rootDir: ./portfolio-app
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: react-frontend
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: database
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: database
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: database
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: database
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: database
          property: password
  - type: static
    name: react-frontend
    rootDir: ./portfolio-app/react-app
    buildCommand: npm install && npm run build
    publishDir: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: laravel-backend
          property: url
  - type: pserv
    name: database
    databaseName: portfolio_db
    databaseUser: portfolio_user
    plan: free
