databases:
  - name: database # Ceci est le nom de votre instance de base de données
    # La propriété 'type: postgres' a été supprimée car elle n'est pas valide ici.
    plan: free # Ou un plan payant si nécessaire
    databaseName: portfolio_db # Spécifie le nom de la base de données

services:
  - type: web
    name: laravel-backend
    runtime: php
    rootDir: ./portfolio-app
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: react-frontend
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: database
          property: database # Ceci récupérera maintenant 'portfolio_db'
      - key: DB_USERNAME
        fromDatabase:
          name: database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: database
          property: password

  - type: web
    name: react-frontend
    runtime: node
    rootDir: ./portfolio-app/react-app
    buildCommand: |
      npm install
      npm run build
      npm install -g serve
    startCommand: serve -s dist -l $PORT
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: laravel-backend
          property: url